# As a general rule, the latest release of Keras is compatible with the latest
# release of TensorFlow as well as the previous release of TensorFlow (in most
# cases, it is actually compatible with several prior TF releases, but that is
# not guaranteed).
#
# -- https://github.com/keras-team/keras/issues/10440#issuecomment-397428200

language: python

branches:
  only:
    - master
    - dev

env:
  - TENSORFLOW='tensorflow' KERAS='keras' ONLY_INSTALL=false


matrix:
  include:
    - os: linux
      python: 3.7
      dist: xenial
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
      dist: xenial
      env: ONLY_INSTALL=true
    - os: linux
      python: 3.5
      env: ONLY_INSTALL=true
    - os: linux
      python: 3.6
      env: ONLY_INSTALL=true

install: 
  - pip install $TENSORFLOW $KERAS
  - if [ $ONLY_INSTALL == true ]; then
       pip install stardist;
    else
       pip install .;
    fi;

script:
  - if [ $ONLY_INSTALL == false ]; then
       echo "huhu";
    fi;
